apiVersion: v1
kind: Secret
metadata:
  # Name of the secret
  name: gitlab-registry
  # Replace 'default' with the actual namespace where the secret will be used
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  # The '.dockerconfigjson' key contains a base64-encoded Docker configuration file.
  # This configuration file contains credentials for Docker registry authentication.
  .dockerconfigjson: <base64-encoded-docker-config-json>

# Instructions:
# 1. Create a Docker config JSON file with your credentials. It typically looks like this:
#    {
#      "auths": {
#        "registry.gitlab.com": {
#          "username": "YOUR_USERNAME",
#          "password": "YOUR_PASSWORD",
#          "email": "YOUR_EMAIL",
#          "auth": "base64-encoded-username-and-password"
#        }
#      }
#    }
# 2. Base64 encode the entire JSON file.
#    You can use a command like 'base64 /path/to/your/config.json' on Linux or macOS.
# 3. Replace <base64-encoded-docker-config-json> in the data field above with your base64-encoded JSON.
# 4. Replace the 'namespace' value from 'default' to your actual namespace where this secret should reside.

